M48
; DRILL file {KiCad (6.0.7)} date Thu Oct 27 11:47:35 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-27T11:47:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X132.75Y-80.5
X132.75Y-108.5
X220.75Y-80.5
X220.75Y-108.5
X308.75Y-80.5
X308.75Y-108.5
T2
X159.0Y-103.5
T0
M30
